// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: platform/platform.proto

package platform

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Empty) Validate() error {
	return nil
}
func (this *Timestamp) Validate() error {
	return nil
}
func (this *LatLng) Validate() error {
	if !(this.Latitude >= -90) {
		return github_com_mwitkow_go_proto_validators.FieldError("Latitude", fmt.Errorf(`value '%v' must be greater than or equal to '-90'`, this.Latitude))
	}
	if !(this.Latitude <= 90) {
		return github_com_mwitkow_go_proto_validators.FieldError("Latitude", fmt.Errorf(`value '%v' must be lower than or equal to '90'`, this.Latitude))
	}
	if !(this.Longitude >= -180) {
		return github_com_mwitkow_go_proto_validators.FieldError("Longitude", fmt.Errorf(`value '%v' must be greater than or equal to '-180'`, this.Longitude))
	}
	if !(this.Longitude <= 180) {
		return github_com_mwitkow_go_proto_validators.FieldError("Longitude", fmt.Errorf(`value '%v' must be lower than or equal to '180'`, this.Longitude))
	}
	return nil
}
func (this *TokenReq) Validate() error {
	return nil
}
func (this *TokenRes) Validate() error {
	return nil
}
